on:
  workflow_call:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - name: Create Project
        id: createProject
        uses: ./
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run tests
        run: |
          pnpm install && pnpm test:coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=${{steps.createProject.outputs.organization}}
            -Dsonar.projectKey=${{steps.createProject.outputs.projectKey}}
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
