on:
  workflow_call:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Create Project
        id: createProject
        uses: ./
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Log outputs
        run: |
          echo ${{steps.outputs.createProject.organization}}
          echo ${{steps.outputs.createProject.projectKey}}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=${{steps.outputs.createProject.organization}}
            -Dsonar.projectKey=${{steps.outputs.createProject.projectKey}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
