on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Git pull
        if: ${{ github.ref == 'refs/heads/main' }}
        run: git pull

      - name: Validate Action
        uses: ./
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
