on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git pull
        if: ${{ github.ref == 'refs/heads/main' }}
        run: git pull
      - name: Validate Action
        uses: ./
        with:
          sonarToken: ${{ secrets.SONAR_TOKEN }}
    env:
      sonarToken: ${{ secrets.SONAR_TOKEN }}
